import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { use } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,acount,notifications,user
}: Readonly<{
  children: React.ReactNode;
  acount: React.ReactNode;
  notifications: React.ReactNode;
  user: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className=" grid grid-cols-2 px-4 py-6 gap-2 items-center">
          {acount}
          {user}
        </div>
        <div className="w-full p-4">{notifications}</div>
      </body>
    </html>
  );
}
